import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "../providers/providers";
import { AuthProvider } from "@/contexts/authentication";
import { NextAuthProvider } from "@/contexts/nextauth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CourseFlow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <NextAuthProvider>
            <Providers>{children}</Providers>
          </NextAuthProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
