import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

import { Providers } from "@/providers/providers";

import SubFooter from "@/components/SubFooter";
import Footer from "@/components/Footer";

import { AuthProvider } from "@/contexts/authentication";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CourseFlow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Providers>{children}</Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
